/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/trig/parser.py
 */
package trld.trig;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import trld.Input;
import static trld.Common.dumpJson;
import static trld.jsonld.Base.VALUE;
import static trld.jsonld.Base.TYPE;
import static trld.jsonld.Base.LANGUAGE;
import static trld.jsonld.Base.ID;
import static trld.jsonld.Base.LIST;
import static trld.jsonld.Base.GRAPH;
import static trld.jsonld.Base.CONTEXT;
import static trld.jsonld.Base.VOCAB;
import static trld.jsonld.Base.BASE;
import static trld.jsonld.Base.PREFIX;
import static trld.jsonld.Base.PREFIX_DELIMS;
import static trld.Rdfterms.RDF_TYPE;
import static trld.Rdfterms.XSD;
import static trld.Rdfterms.XSD_DOUBLE;
import static trld.Rdfterms.XSD_INTEGER;
import static trld.trig.Parser.*;


public class ParserError extends RuntimeException { // LINE: 58
  ParserError() { };
  ParserError(String msg) { super(msg); };
  public NotationError error; // LINE: 60
  public Integer lno; // LINE: 61
  public Integer cno; // LINE: 62

  public ParserError(NotationError error, Integer lno, Integer cno) { // LINE: 64
    super(error.toString()); // LINE: 65
    this.error = error; // LINE: 66
    this.lno = lno; // LINE: 67
    this.cno = cno; // LINE: 68
  }

  public String toString() { // LINE: 70
    return "Notation error at line " + this.lno + ", column " + this.cno + ": " + this.error; // LINE: 71
  }
}
