/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/trig/parser.py
 */
package trld.trig;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import static trld.platform.Common.jsonEncode;
import trld.platform.Input;
import static trld.jsonld.Base.VALUE;
import static trld.jsonld.Base.TYPE;
import static trld.jsonld.Base.LANGUAGE;
import static trld.jsonld.Base.ID;
import static trld.jsonld.Base.LIST;
import static trld.jsonld.Base.GRAPH;
import static trld.jsonld.Base.CONTEXT;
import static trld.jsonld.Base.VOCAB;
import static trld.jsonld.Base.BASE;
import static trld.jsonld.Base.PREFIX;
import static trld.jsonld.Base.PREFIX_DELIMS;
import static trld.jsonld.Star.ANNOTATION;
import static trld.jsonld.Star.ANNOTATED_TYPE_KEY;
import static trld.Rdfterms.RDF_TYPE;
import static trld.Rdfterms.XSD;
import static trld.Rdfterms.XSD_DOUBLE;
import static trld.Rdfterms.XSD_INTEGER;
import static trld.trig.Parser.*;


public class ReadGraph extends ReadNodes {
  public ReadGraph(/*@Nullable*/ ParserState parent) { super(parent); };

  public Map.Entry<ParserState, Object> consume(String c, Object prevValue) {
    if ((prevValue instanceof String && !prevValue.equals(TYPE))) {
      throw new NotationError("Directive not allowed in graph: " + prevValue);
    }
    ReadNodes readnodes = (ReadNodes) ((ReadNodes) this.parent);
    if ((this.expectGraph || (this.openBrace && !c.equals("|")))) {
      throw new NotationError("Nested graphs are not allowed in TriG");
    }
    if ((c == null && ((Object) "}") == null || c != null && (c).equals("}"))) {
      if (this.node != null) {
        if ((this.p != null && prevValue != null)) {
          this.fillNode(prevValue);
        }
        this.nextNode();
      }
      if (readnodes.node == null) {
        readnodes.nodes.addAll(this.nodes);
      } else {
        readnodes.node.put(GRAPH, this.nodes);
        readnodes.nextNode();
      }
      return new KeyValue(readnodes, null);
    } else {
      return super.consume(c, prevValue);
    }
  }
}
