/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/trig/parser.py
 */
package trld.trig;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import trld.Input;
import static trld.Common.dumpJson;
import static trld.jsonld.Base.VALUE;
import static trld.jsonld.Base.TYPE;
import static trld.jsonld.Base.LANGUAGE;
import static trld.jsonld.Base.ID;
import static trld.jsonld.Base.LIST;
import static trld.jsonld.Base.GRAPH;
import static trld.jsonld.Base.CONTEXT;
import static trld.jsonld.Base.VOCAB;
import static trld.jsonld.Base.BASE;
import static trld.jsonld.Base.PREFIX;
import static trld.jsonld.Base.PREFIX_DELIMS;
import static trld.Rdfterms.RDF_TYPE;
import static trld.Rdfterms.XSD;
import static trld.Rdfterms.XSD_DOUBLE;
import static trld.Rdfterms.XSD_INTEGER;
import static trld.trig.Parser.*;


public class ReadBase extends ReadDecl { // LINE: 546
  ReadBase(ReadNodes parent, Boolean finalDot) { super(parent, finalDot); };
  public /*@Nullable*/ String base; // LINE: 548

  public void init() { // LINE: 550
    this.base = null; // LINE: 551
  }

  public boolean moreParts(Map value) { // LINE: 553
    if (this.base == null) { // LINE: 554
      this.base = (String) value.get(ID); // LINE: 555
    }
    return false; // LINE: 556
  }

  public void declare() { // LINE: 558
    this.parent.context.put(BASE, this.base); // LINE: 559
  }
}
