/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/jsonld/base.py
 */
package trld.jsonld;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import static trld.jsonld.Base.*;


public class JsonLdError extends RuntimeException {
  public JsonLdError() { };
  public JsonLdError(String msg) { super(msg); };
}
