/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/jsonld/context.py
 */
package trld.jsonld;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import static trld.Common.loadJson;
import static trld.Common.warning;
import static trld.Common.resolveIri;
import static trld.jsonld.Base.*;
import static trld.jsonld.Context.*;


public class Term { // LINE: 456
  public String iri; // LINE: 458
  public Boolean isPrefix; // LINE: 459
  public Boolean isProtected; // LINE: 460
  public Boolean isReverseProperty; // LINE: 461
  public /*@Nullable*/ String baseUrl; // LINE: 462
  public Boolean hasLocalContext; // LINE: 463
  public List<String> container; // LINE: 464
  public /*@Nullable*/ String direction; // LINE: 465
  public /*@Nullable*/ String index; // LINE: 466
  public /*@Nullable*/ String language; // LINE: 467
  public /*@Nullable*/ String nestValue; // LINE: 468
  public /*@Nullable*/ String typeMapping; // LINE: 469
  public /*@Nullable*/ Object localContext; // LINE: 471
  public Map<String, /*@Nullable*/ Context> cachedContexts; // LINE: 472
  public Set remoteContexts; // LINE: 473

  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined) {
    this(activeContext, localContext, term, value, defined, null);
  }
  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined, String baseUrl) {
    this(activeContext, localContext, term, value, defined, baseUrl, false);
  }
  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined, String baseUrl, Boolean isprotected) {
    this(activeContext, localContext, term, value, defined, baseUrl, isprotected, false);
  }
  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined, String baseUrl, Boolean isprotected, Boolean overrideProtected) {
    this(activeContext, localContext, term, value, defined, baseUrl, isprotected, overrideProtected, null);
  }
  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined, String baseUrl, Boolean isprotected, Boolean overrideProtected, Set remoteContexts) {
    this(activeContext, localContext, term, value, defined, baseUrl, isprotected, overrideProtected, remoteContexts, true);
  }
  public Term(Context activeContext, Map<String, Object> localContext, String term, Object value, Map<String, Boolean> defined, String baseUrl, Boolean isprotected, Boolean overrideProtected, Set remoteContexts, Boolean validateScoped) { // LINE: 475
    this.isPrefix = false; // LINE: 488
    this.isProtected = (isprotected instanceof Boolean ? (Boolean) isprotected : false); // LINE: 489
    this.isReverseProperty = false; // LINE: 490
    this.container = new ArrayList<>(); // LINE: 491
    this.direction = null; // LINE: 492
    this.index = null; // LINE: 493
    this.language = null; // LINE: 494
    this.nestValue = null; // LINE: 495
    this.typeMapping = null; // LINE: 496
    if (remoteContexts == null) { // LINE: 498
      remoteContexts = new HashSet(); // LINE: 499
    }
    this.baseUrl = null; // LINE: 501
    this.hasLocalContext = false; // LINE: 502
    this.localContext = null; // LINE: 503
    this.remoteContexts = remoteContexts; // LINE: 504
    this.cachedContexts = new HashMap<>(); // LINE: 505
    if (defined.containsKey(term)) { // LINE: 509
      Boolean definedTerm = (Boolean) defined.get(term); // LINE: 510
      if (definedTerm) { // LINE: 511
        return; // LINE: 512
      } else {
        throw new CyclicIriMappingError(term); // LINE: 514
      }
    }
    if ((term == null && ((Object) "") == null || term != null && (term).equals(""))) { // LINE: 516
      throw new InvalidTermDefinitionError(); // LINE: 517
    }
    defined.put(term, false); // LINE: 519
    if ((term == null && ((Object) TYPE) == null || term != null && (term).equals(TYPE))) { // LINE: 525
      if ((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10))) { // LINE: 526
        throw new KeywordRedefinitionError(); // LINE: 527
      }
      if ((!(value instanceof Map) || !(((((Map) value).get(CONTAINER) == null && ((Object) SET) == null || ((Map) value).get(CONTAINER) != null && (((Map) value).get(CONTAINER)).equals(SET)) || ((Map) value).containsKey(PROTECTED))))) { // LINE: 529
        throw new KeywordRedefinitionError(); // LINE: 531
      }
    } else if (KEYWORDS.contains(term)) { // LINE: 534
      throw new KeywordRedefinitionError(term); // LINE: 535
    }
    if (hasKeywordForm(term)) { // LINE: 537
      warning("Term " + term + " looks like a keyword (it matches the ABNF rule \"@\"1*ALPHA from [RFC5234])"); // LINE: 538
    }
    /*@Nullable*/ Term prevDfn = (/*@Nullable*/ Term) activeContext.terms.remove(term); // LINE: 542
    Boolean simpleTerm; // LINE: 544
    Map dfn; // LINE: 547
    if ((value == null || value instanceof String)) { // LINE: 548
      dfn = new HashMap<>(); // LINE: 549
      dfn.put(ID, (String) value); // LINE: 550
      simpleTerm = value instanceof String; // LINE: 551
    } else {
      if (!(value instanceof Map)) { // LINE: 554
        throw new InvalidTermDefinitionError(value.toString()); // LINE: 555
      }
      dfn = (Map) value; // LINE: 556
      simpleTerm = false; // LINE: 557
    }
    if (dfn.containsKey(PROTECTED)) { // LINE: 563
      if ((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10))) { // LINE: 564
        throw new InvalidTermDefinitionError(dfn.toString()); // LINE: 565
      }
      Object isProtected = (Object) dfn.get(PROTECTED); // LINE: 566
      if (isProtected instanceof Boolean) { // LINE: 567
        this.isProtected = (Boolean) isProtected; // LINE: 568
      } else {
        throw new InvalidProtectedValueError(); // LINE: 570
      }
    }
    Object typeMapping = (Object) dfn.get(TYPE); // LINE: 573
    if (typeMapping instanceof String) { // LINE: 575
      this.typeMapping = (String) activeContext.expandInitVocabIri((String) typeMapping, localContext, defined); // LINE: 577
      if (((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10)) && new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) JSON, NONE}))).contains(this.typeMapping))) { // LINE: 579
        throw new InvalidTypeMappingError(); // LINE: 581
      } else if ((!new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) ID, JSON, NONE, VOCAB}))).contains(this.typeMapping) && !(isIri(this.typeMapping)))) { // LINE: 583
        throw new InvalidTypeMappingError(this.typeMapping); // LINE: 584
      }
    } else if (typeMapping != null) { // LINE: 585
      throw new InvalidTypeMappingError(); // LINE: 586
    }
    if (dfn.containsKey(REVERSE)) { // LINE: 589
      Object rev = (Object) dfn.get(REVERSE); // LINE: 590
      if ((dfn.containsKey(ID) || dfn.containsKey(NEST))) { // LINE: 592
        throw new InvalidReversePropertyError(); // LINE: 593
      }
      if (!(rev instanceof String)) { // LINE: 595
        throw new InvalidIriMappingError(); // LINE: 596
      }
      if (hasKeywordForm((String) rev)) { // LINE: 599
        warning("Reverse " + rev + " for term " + term + " has the form of a keyword"); // LINE: 600
        return; // LINE: 601
      }
      this.iri = ((String) activeContext.expandInitVocabIri((String) rev, localContext, defined)); // LINE: 603
      if (!((isBlank(this.iri) || isIri(this.iri)))) { // LINE: 604
        throw new InvalidIriMappingError(); // LINE: 605
      }
      if (dfn.containsKey(CONTAINER)) { // LINE: 607
        this.container = (List<String>) Builtins.sorted(asList(dfn.get(CONTAINER))); // LINE: 608
        if (!new HashSet(new ArrayList<>(Arrays.asList(new Object[] {(Object) SET, INDEX, null}))).contains(dfn.get(CONTAINER))) { // LINE: 609
          throw new InvalidReversePropertyError(); // LINE: 610
        }
      }
      this.isReverseProperty = true; // LINE: 612
      activeContext.terms.put(term, this); // LINE: 614
      defined.put(term, true); // LINE: 615
      return; // LINE: 616
    }
    if ((dfn.containsKey(ID) && !term.equals(dfn.get(ID)))) { // LINE: 619
      String id = (String) ((String) dfn.get(ID)); // LINE: 620
      if (id == null) { // LINE: 622
        this.iri = null; // LINE: 624
      } else {
        if (!(id instanceof String)) { // LINE: 628
          throw new InvalidIriMappingError(); // LINE: 629
        }
        if ((!KEYWORDS.contains(id) && hasKeywordForm((String) id))) { // LINE: 631
          warning("Id " + id + " for term " + term + " is not a keyword but has the form of a keyword"); // LINE: 632
        }
        this.iri = ((String) activeContext.expandInitVocabIri((String) id, localContext, defined)); // LINE: 635
        if ((this.iri == null || !((KEYWORDS.contains(this.iri) || isBlank(this.iri) || isIri(this.iri))))) { // LINE: 636
          return; // LINE: 638
        }
        if ((this.iri == null && ((Object) CONTEXT) == null || this.iri != null && (this.iri).equals(CONTEXT))) { // LINE: 640
          throw new InvalidKeywordAliasError(); // LINE: 641
        }
        if ((term.substring(1, term.length() - 1).contains(":") || term.contains("/"))) { // LINE: 644
          defined.put(term, true); // LINE: 646
          if (!activeContext.expandInitVocabIri(term, localContext, defined).equals(this.iri)) { // LINE: 648
          }
        } else if ((simpleTerm && (PREFIX_DELIMS.contains(this.iri.substring(this.iri.length() - 1, this.iri.length() - 1 + 1)) || isBlank(this.iri)))) { // LINE: 654
          this.isPrefix = true; // LINE: 655
        }
      }
    } else if (term.substring(1).contains(":")) { // LINE: 658
      Integer idx = (Integer) term.indexOf(":"); // LINE: 660
      String prefix = term.substring(0, idx); // LINE: 661
      String suffix = term.substring(idx + 1); // LINE: 662
      if (localContext.containsKey(prefix)) { // LINE: 665
        new Term(activeContext, localContext, prefix, localContext.get(prefix), defined); // LINE: 666
      }
      if (activeContext.terms.containsKey(prefix)) { // LINE: 669
        this.iri = activeContext.terms.get(prefix).iri + suffix; // LINE: 670
      } else {
        this.iri = term; // LINE: 674
      }
    } else if (term.contains("/")) { // LINE: 677
      this.iri = ((String) activeContext.expandVocabIri(term)); // LINE: 680
      if (!(isIri(this.iri))) { // LINE: 681
        throw new InvalidIriMappingError(); // LINE: 682
      }
    } else if ((term == null && ((Object) TYPE) == null || term != null && (term).equals(TYPE))) { // LINE: 685
      this.iri = TYPE; // LINE: 686
    } else if (activeContext.vocabularyMapping != null) { // LINE: 689
      this.iri = activeContext.vocabularyMapping + term; // LINE: 690
    } else {
      throw new InvalidIriMappingError(term + ": " + value.toString()); // LINE: 692
    }
    if (dfn.containsKey(CONTAINER)) { // LINE: 695
      Object container = (Object) dfn.get(CONTAINER); // LINE: 696
      /*@Nullable*/ Set containerTerms = null; // LINE: 698
      if (container instanceof List) { // LINE: 699
        containerTerms = (Set) new HashSet((List) container); // LINE: 700
        if ((containerTerms.contains(SET) && !containerTerms.contains(LIST))) { // LINE: 701
          containerTerms.remove(SET); // LINE: 702
        }
      }
      if ((!((container instanceof String && CONTAINER_KEYWORDS.contains(container))) && !((containerTerms != null && (containerTerms.size() == 0 || (containerTerms.size() == 1 && containerTerms.stream().allMatch(t -> CONTAINER_KEYWORDS.contains(t))) || (containerTerms == null && ((Object) new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) GRAPH, ID})))) == null || containerTerms != null && (containerTerms).equals(new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) GRAPH, ID}))))) || (containerTerms == null && ((Object) new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) GRAPH, INDEX})))) == null || containerTerms != null && (containerTerms).equals(new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) GRAPH, INDEX}))))) || new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) INDEX, GRAPH, ID, TYPE, LANGUAGE}))).contains(new ArrayList(containerTerms).get(0))))))) { // LINE: 703
        throw new InvalidContainerMappingError((String) container); // LINE: 714
      }
      if ((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10))) { // LINE: 717
        if ((!(container instanceof String) || new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) GRAPH, ID, TYPE}))).contains(container))) { // LINE: 718
          throw new InvalidContainerMappingError((String) container.toString()); // LINE: 719
        }
      }
      this.container = (List<String>) Builtins.sorted(asList(((Object) container))); // LINE: 722
      if (this.container.contains(TYPE)) { // LINE: 725
        if (this.typeMapping == null) { // LINE: 727
          this.typeMapping = ID; // LINE: 728
        } else if (!new HashSet(new ArrayList<>(Arrays.asList(new String[] {(String) ID, VOCAB}))).contains(this.typeMapping)) { // LINE: 730
          throw new InvalidTypeMappingError(); // LINE: 731
        }
      }
    }
    if (dfn.containsKey(INDEX)) { // LINE: 734
      if (((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10)) || !this.container.contains(INDEX))) { // LINE: 736
        throw new InvalidTermDefinitionError(value.toString()); // LINE: 737
      }
      Object index = (Object) dfn.get(INDEX); // LINE: 739
      if (!(index instanceof String)) { // LINE: 740
        throw new InvalidTermDefinitionError(value.toString()); // LINE: 741
      }
      if (!(isIri(activeContext.expandVocabIri((String) index)))) { // LINE: 742
        throw new InvalidTermDefinitionError(value.toString()); // LINE: 743
      }
      this.index = (String) index; // LINE: 745
    }
    this.hasLocalContext = (Boolean) dfn.containsKey(CONTEXT); // LINE: 748
    if (this.hasLocalContext) { // LINE: 749
      if ((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10))) { // LINE: 751
        throw new InvalidTermDefinitionError(dfn.toString()); // LINE: 752
      }
      this.localContext = (Object) dfn.get(CONTEXT); // LINE: 763
      this.baseUrl = baseUrl; // LINE: 764
    }
    if ((dfn.containsKey(LANGUAGE) && !dfn.containsKey(TYPE))) { // LINE: 767
      Object lang = (Object) dfn.get(LANGUAGE); // LINE: 769
      if ((!(lang instanceof String) && lang != null)) { // LINE: 770
        throw new InvalidLanguageMappingError(); // LINE: 771
      }
      if (!(isLangTag((String) lang))) { // LINE: 772
        warning("Language tag " + lang + " in term " + term + " is not well-formed"); // LINE: 773
      }
      this.language = (lang == null ? NULL : ((String) lang).toLowerCase()); // LINE: 776
    }
    if ((dfn.containsKey(DIRECTION) && !dfn.containsKey(TYPE))) { // LINE: 779
      Object dir = (Object) dfn.get(DIRECTION); // LINE: 781
      if ((!DIRECTIONS.contains(dir) && dir != null)) { // LINE: 782
        throw new InvalidBaseDirectionError(); // LINE: 783
      }
      this.direction = (dir == null ? NULL : ((String) dir)); // LINE: 786
    }
    if (dfn.containsKey(NEST)) { // LINE: 789
      if ((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10))) { // LINE: 791
        throw new InvalidTermDefinitionError(); // LINE: 792
      }
      this.nestValue = ((String) dfn.get(NEST)); // LINE: 794
      if ((!(this.nestValue instanceof String) || (!this.nestValue.equals(NEST) && KEYWORDS.contains(this.nestValue)))) { // LINE: 795
        throw new InvalidNestValueError(); // LINE: 797
      }
    }
    if (dfn.containsKey(PREFIX)) { // LINE: 800
      if (((activeContext.processingMode == null && ((Object) JSONLD10) == null || activeContext.processingMode != null && (activeContext.processingMode).equals(JSONLD10)) || term.contains(":") || term.contains("/"))) { // LINE: 802
        throw new InvalidTermDefinitionError(); // LINE: 803
      }
      this.isPrefix = ((Boolean) dfn.get(PREFIX)); // LINE: 805
      if (!(this.isPrefix instanceof Boolean)) { // LINE: 806
        throw new InvalidPrefixValueError(); // LINE: 807
      }
      if ((this.isPrefix && KEYWORDS.contains(this.iri))) { // LINE: 809
        throw new InvalidTermDefinitionError(); // LINE: 810
      }
    }
    if ((!(overrideProtected) && prevDfn != null && prevDfn.isProtected)) { // LINE: 817
      this.isProtected = (Boolean) prevDfn.isProtected; // LINE: 819
      if (!(this.matches(prevDfn))) { // LINE: 821
        throw new ProtectedTermRedefinitionError(); // LINE: 822
      }
    }
    activeContext.terms.put(term, this); // LINE: 825
    defined.put(term, true); // LINE: 826
  }

  public Context getLocalContext(Context activeContext) {
    return this.getLocalContext(activeContext, true);
  }
  public Context getLocalContext(Context activeContext, Boolean propagate) { // LINE: 828
    String cacheKey = activeContext.hashCode() + ":" + propagate.toString(); // LINE: 829
    /*@Nullable*/ Context cached = (/*@Nullable*/ Context) this.cachedContexts.get(cacheKey); // LINE: 830
    Boolean overrideProtected = propagate; // LINE: 834
    if (cached == null) { // LINE: 836
      cached = activeContext.getContext(this.localContext, this.baseUrl, new HashSet(this.remoteContexts), overrideProtected, false); // LINE: 837
      this.cachedContexts.put(cacheKey, cached); // LINE: 842
    }
    if ((!(this.localContext instanceof Map) || !((Map) this.localContext).containsKey(PROPAGATE))) { // LINE: 844
      cached.propagate = propagate; // LINE: 846
    }
    return cached; // LINE: 848
  }

  public boolean matches(Object other) { // LINE: 850
    if (!(other instanceof Term)) { // LINE: 851
      return false; // LINE: 852
    }
    return ((this.iri == null && ((Object) ((Term) other).iri) == null || this.iri != null && (this.iri).equals(((Term) other).iri)) && (this.isPrefix == null && ((Object) ((Term) other).isPrefix) == null || this.isPrefix != null && (this.isPrefix).equals(((Term) other).isPrefix)) && (this.isReverseProperty == null && ((Object) ((Term) other).isReverseProperty) == null || this.isReverseProperty != null && (this.isReverseProperty).equals(((Term) other).isReverseProperty)) && (this.baseUrl == null && ((Object) ((Term) other).baseUrl) == null || this.baseUrl != null && (this.baseUrl).equals(((Term) other).baseUrl)) && (this.hasLocalContext == null && ((Object) ((Term) other).hasLocalContext) == null || this.hasLocalContext != null && (this.hasLocalContext).equals(((Term) other).hasLocalContext)) && (this.container == null && ((Object) ((Term) other).container) == null || this.container != null && (this.container).equals(((Term) other).container)) && (this.direction == null && ((Object) ((Term) other).direction) == null || this.direction != null && (this.direction).equals(((Term) other).direction)) && (this.index == null && ((Object) ((Term) other).index) == null || this.index != null && (this.index).equals(((Term) other).index)) && (this.language == null && ((Object) ((Term) other).language) == null || this.language != null && (this.language).equals(((Term) other).language)) && (this.nestValue == null && ((Object) ((Term) other).nestValue) == null || this.nestValue != null && (this.nestValue).equals(((Term) other).nestValue)) && (this.typeMapping == null && ((Object) ((Term) other).typeMapping) == null || this.typeMapping != null && (this.typeMapping).equals(((Term) other).typeMapping)) && (this.localContext == null && ((Object) ((Term) other).localContext) == null || this.localContext != null && (this.localContext).equals(((Term) other).localContext))); // LINE: 854
  }
}
