org.gradle.daemon=true
groovyVersion=4.0.27
spockVersion=2.3-groovy-4.0
byteBuddyVersion = 1.17.6
codeNarcVersion=3.6.0-groovy-4.0
servletApiVersion = 4.0.3
jettyVersion = 12.0.38
prometheusVersion = 1.8.0
prometheusSimpleclientVersion = 0.16.0
slf4jVersion = 2.0.18
logbackVersion = 1.5.38
resilience4jVersion = 1.7.1
hikariVersion = 4.0.3
httpComponentsCoreVersion = 5.3.6
httpComponentsClientVersion = 5.5
systemProp.https.protocols=TLSv1.1,TLSv1.2
guavaVersion=33.6.0-jre
jacocoVersion=0.8.13
jacksonVersion=2.21.5
jenaVersion=6.2.0
