prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

construct {

    ?property rdfs:domain ?domain .
    ?property rdfs:range ?range .

} where {

    bind("http://libris.kb.se/def/terms#" as ?strvocab)

    ?property
        rdfs:subPropertyOf|owl:equivalentProperty ?baseproperty ;
        #rdfs:isDefinedBy ?vocab .
        filter(strstarts(str(?property), ?strvocab))
    {
        ?baseproperty rdfs:domain ?basedomain .
        ?domain rdfs:subClassOf|owl:equivalentClass ?basedomain .
        #?domain rdfs:isDefinedBy ?vocab .
        #filter(strstarts(str(?domain), ?strvocab))
    } union {
        ?baseproperty rdfs:range ?baserange .
        ?range rdfs:subClassOf|owl:equivalentClass ?baserange .
        #?range rdfs:isDefinedBy ?vocab .
        #filter(strstarts(str(?range), ?strvocab))
    }

}
