/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/rdfterms.py
 */
package trld;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;


public class Rdfterms {
  public static final String RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
  public static final String RDF_TYPE = RDF + "type";
  public static final String RDF_VALUE = RDF + "value";
  public static final String RDF_LIST = RDF + "List";
  public static final String RDF_FIRST = RDF + "first";
  public static final String RDF_REST = RDF + "rest";
  public static final String RDF_NIL = RDF + "nil";
  public static final String RDF_DIRECTION = RDF + "direction";
  public static final String RDF_LANGUAGE = RDF + "language";
  public static final String RDF_JSON = RDF + "JSON";
  public static final String RDF_LANGSTRING = RDF + "langString";
  public static final String XSD = "http://www.w3.org/2001/XMLSchema#";
  public static final String XSD_BOOLEAN = XSD + "boolean";
  public static final String XSD_DECIMAL = XSD + "decimal";
  public static final String XSD_DOUBLE = XSD + "double";
  public static final String XSD_INTEGER = XSD + "integer";
  public static final String XSD_STRING = XSD + "string";
  public static final String I18N = "https://www.w3.org/ns/i18n#";
}
