/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/rdfterms.py
 */
package trld;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;


public class Rdfterms {
  public static final String RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"; // LINE: 1
  public static final String RDF_TYPE = RDF + "type"; // LINE: 2
  public static final String RDF_VALUE = RDF + "value"; // LINE: 3
  public static final String RDF_LIST = RDF + "List"; // LINE: 4
  public static final String RDF_FIRST = RDF + "first"; // LINE: 5
  public static final String RDF_REST = RDF + "rest"; // LINE: 6
  public static final String RDF_NIL = RDF + "nil"; // LINE: 7
  public static final String RDF_DIRECTION = RDF + "direction"; // LINE: 8
  public static final String RDF_LANGUAGE = RDF + "language"; // LINE: 9
  public static final String RDF_JSON = RDF + "JSON"; // LINE: 10
  public static final String RDF_LANGSTRING = RDF + "langString"; // LINE: 11
  public static final String XSD = "http://www.w3.org/2001/XMLSchema#"; // LINE: 13
  public static final String XSD_BOOLEAN = XSD + "boolean"; // LINE: 14
  public static final String XSD_DECIMAL = XSD + "decimal"; // LINE: 15
  public static final String XSD_DOUBLE = XSD + "double"; // LINE: 16
  public static final String XSD_INTEGER = XSD + "integer"; // LINE: 17
  public static final String XSD_STRING = XSD + "string"; // LINE: 18
  public static final String I18N = "https://www.w3.org/ns/i18n#"; // LINE: 20
}
