/**
 * This file was automatically generated by the TRLD transpiler.
 * Source: trld/tvm/mapmaker.py
 */
package trld.tvm;

//import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Function;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.io.*;

import trld.Builtins;
import trld.KeyValue;

import static trld.jsonld.Base.CONTEXT;
import static trld.jsonld.Base.GRAPH;
import static trld.jsonld.Base.ID;
import static trld.jsonld.Base.LIST;
import static trld.jsonld.Base.REVERSE;
import static trld.jsonld.Base.TYPE;
import static trld.jsonld.Base.VOCAB;
import static trld.jsonld.Base.asList;
import static trld.jsonld.extras.Index.makeIndex;
import static trld.tvm.Mapmaker.*;


public class BaseRelation { // LINE: 55
  public /*@Nullable*/ String rel; // LINE: 56
  public String base; // LINE: 57
  public Integer priority = -1; // LINE: 58
  public BaseRelation(String rel, String base) {
    this(rel, base, -1);
  }
  public BaseRelation(String rel, String base, Integer priority) {
    this.rel = rel;
    this.base = base;
    this.priority = priority;
  }
}
