apply plugin: 'application'
apply plugin: 'groovy'
apply plugin: 'com.gradleup.shadow'

repositories {
    mavenCentral()
    maven { url = "https://jitpack.io/" }
}

// Don't blame me for this TRAVESTY. It is a necessity because of the versioning of xml-apis (2.0.2 which gradle otherwise chooses is OLDER (and broken) despite the version.)
configurations.all {
    resolutionStrategy {
        force "xml-apis:xml-apis:1.4.01"
    }
}

dependencies {

    // Logging
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation "ch.qos.logback:logback-core:${logbackVersion}"

    // XL dependencies
    implementation(project(':whelk-core'))
    implementation "io.prometheus:prometheus-metrics-core:${prometheusVersion}"
    implementation "io.prometheus:prometheus-metrics-exporter-pushgateway:${prometheusVersion}"

    testImplementation "org.spockframework:spock-core:${spockVersion}"
}

test {
    useJUnitPlatform()
}

test.testLogging {
    showStandardStreams = true
    exceptionFormat = "full"
}

application {
    mainClass = 'whelk.importer.Main'
}

shadowJar {
    archiveClassifier = null // removes `-all` in the filename of the created .jar
}

jar {
    dependsOn ':whelk-core:jar'
    dependsOn(shadowJar)

    manifest {
        attributes 'Implementation-Title':'Libris XL metadata importer',
                'Implementation-Version': '1.0',
                'Main-class': application.mainClass
    }

    archiveClassifier = "nonfat"
    enabled = false
}
