package whelk.util;

import com.ibm.icu.text.Transliterator;
import groovy.yaml.YamlSlurper;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static whelk.util.Unicode.normalize;

/**
 * Convert mappings from LOC's ScriptShifter in homegrown YAML format to ICU transform rules
 * https://github.com/lcnetdev/transliterator/
 */
public class ScriptShifterShifter {

    static final String BASE = "https://raw.githubusercontent.com/lcnetdev/transliterator/main/scriptshifter/tables/data/";

    static final Map<String, String> tables = Map.ofEntries(
            Map.entry("armenian", "hy-Latn-t-hy-Armn-m0-alaloc"),
            Map.entry("azerbaijani", "az-Latn-t-az-Cyrl-m0-alaloc"),
            Map.entry("chinese", "zh-Latn-t-zh-Hani-m0-alaloc"),
            Map.entry("church_slavonic", "cu-Latn-t-cu-Cyrs-m0-alaloc"),
            Map.entry("ethiopic", "am-Latn-t-am-Ethi-m0-alaloc"),
            Map.entry("georgian", "ka-Latn-t-ka-m0-alaloc"),
            Map.entry("hindi", "hi-Latn-t-hi-Deva-m0-alaloc"),
            Map.entry("kyrgyz", "ky-Latn-t-ky-Cyrl-m0-alaloc"),
            Map.entry("mongolian_mongol_bichig", "mn-Latn-t-mn-Mong-m0-alaloc"),
            Map.entry("tajik", "tg-Latn-t-tg-Cyrl-m0-alaloc"),
            Map.entry("tatar", "tt-Latn-t-tt-Cyrl-m0-alaloc"),
            Map.entry("turkmen", "tk-Latn-t-tk-Cyrl-m0-alaloc"),
            Map.entry("uzbek", "uz-Latn-t-uz-Cyrl-m0-alaloc"),

            /* "Multi-purpose transliteration for non-Slavic Cyrillic scripts: Abaza, Abkhaz, Adygei, Aisor, Altai,
            Avar, Azeri, Balkar, Bashkir, Buryat, Chechen, Chukchi, Chuvash, Dargwa, Dungan, Eskimo, Even, Evenki,
            Gagauz, Ingush, Inuit, Kabardian, Kalmyk, Karachay, Karachay-Balkar, Karakalpak, Karelian, Khakass,
            Khanty, Komi, Komi-Permyak, Koryak, Kumyk, Lak, Lapp, Lezghian, Lithuanian, Mansi, Mari, Moldovan,
            Molodstov, Mordvin, Nanai, Nenets, Nivkh, Nogai, Ossetic, Permyak, Romanian, Romany, Selkup, Shor,
            Tabasaran, Tat, Tuva, Udekhe, Udmurt, Yakut."
            https://github.com/lcnetdev/transliterator/blob/main/scriptshifter/tables/data/index.yml
            */
            Map.entry("asian_cyrillic", "und-Latn-t-und-Cyrl-m0-alaloc")
    );

    static final List<String> SKIP_PARENTS = List.of("_ignore_base");

    public static void run(String outputPath) throws IOException {
        for (Map.Entry<String, String> entry : tables.entrySet()) {
            String name = entry.getKey();
            String id = entry.getValue();
            Map<String, Object> table = load(name);

            StringBuilder s = new StringBuilder()
                    .append("# *** This file was automatically generated by ").append(ScriptShifterShifter.class.getName()).append(" ***\n")
                    .append("# Source: ").append(url(name)).append("\n")
                    .append("# ICU transform rules\n")
                    .append("\n")
                    .append("# ").append(id).append("\n\n");

            // Sort on key length so that rules don't shadow each other
            s.append("# script_to_roman\n");
            Map<String, String> map = normalizeEntries(sectionMap(table, "script_to_roman"));
            for (Map.Entry<String, String> e : sortedByKeyLengthDescending(map)) {
                s.append(quote(e.getKey())).append(" > ").append(quote(e.getValue())).append(" ;\n");
            }

            s.append("# roman_to_script\n");
            map = normalizeEntries(sectionMap(table, "roman_to_script"));
            for (Map.Entry<String, String> e : sortedByKeyLengthDescending(map)) {
                s.append(quote(e.getValue())).append(" < ").append(quote(e.getKey())).append(" ;\n");
            }

            String rules = s.toString();
            testCompile(id, rules);

            String file = id + ".txt";
            Files.writeString(new File(outputPath, file).toPath(), rules, StandardCharsets.UTF_8);
            System.out.println(file);
        }
    }

    static String url(String name) {
        return BASE + name + ".yml";
    }

    @SuppressWarnings("unchecked")
    static Map<String, Object> load(String name) throws IOException {
        Map<String, Object> table;
        try (InputStream is = URI.create(url(name)).toURL().openStream()) {
            table = (Map<String, Object>) new YamlSlurper().parse(is);
        }

        Map<String, Object> general = (Map<String, Object>) table.getOrDefault("general", Map.of());
        Object inherits = general.get("inherits") != null ? general.get("inherits") : general.get("parents");
        for (Object parentName : asList(inherits != null ? inherits : List.of())) {
            if (SKIP_PARENTS.contains(parentName)) {
                continue;
            }
            Map<String, Object> parent = load((String) parentName);
            mergeSection(table, parent, "script_to_roman");
            mergeSection(table, parent, "roman_to_script");
        }

        return table;
    }

    @SuppressWarnings("unchecked")
    private static void mergeSection(Map<String, Object> table, Map<String, Object> parent, String section) {
        Map<String, Object> merged = new LinkedHashMap<>(sectionMap(parent, section));
        merged.putAll(sectionMap(table, section));
        ((Map<String, Object>) table.computeIfAbsent(section, k -> new LinkedHashMap<>())).put("map", merged);
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> sectionMap(Map<String, Object> table, String section) {
        Map<String, Object> s = (Map<String, Object>) table.get(section);
        Map<String, Object> map = s != null ? (Map<String, Object>) s.get("map") : null;
        return map != null ? map : Map.of();
    }

    private static Map<String, String> normalizeEntries(Map<String, Object> map) {
        Map<String, String> result = new LinkedHashMap<>();
        map.forEach((k, v) -> result.put(normalize(k), normalize(v != null ? v.toString() : "")));
        return result;
    }

    private static List<Map.Entry<String, String>> sortedByKeyLengthDescending(Map<String, String> map) {
        List<Map.Entry<String, String>> entries = new ArrayList<>(map.entrySet());
        entries.sort((a, b) -> b.getKey().length() - a.getKey().length());
        return entries;
    }

    static String quote(String s) {
        // TODO...
        return "'".equals(s) ? "\\'\\" : "'" + s + "'";
    }

    static void testCompile(String id, String rules) {
        try {
            Transliterator.createFromRules(id, rules, Transliterator.REVERSE);
        }
        catch (Exception e) {
            System.err.println("Warning: could not create rules for " + id + ": " + e);
            e.printStackTrace(System.err);
        }
    }

    static List<?> asList(Object o) {
        return o instanceof List ? (List<?>) o : List.of(o);
    }

    public static void main(String[] args) throws IOException {
        run("whelk-core/src/main/resources/romanizer/loc/");
    }
}
